<CODEGEN_FILENAME><INTERFACE_NAME>.http</CODEGEN_FILENAME>
<REQUIRES_CODEGEN_VERSION>5.7.5</REQUIRES_CODEGEN_VERSION>
<REQUIRES_USERTOKEN>SERVER_PROTOCOL</REQUIRES_USERTOKEN>
<REQUIRES_USERTOKEN>SERVER_NAME</REQUIRES_USERTOKEN>
<REQUIRES_USERTOKEN>SERVER_HTTPS_PORT</REQUIRES_USERTOKEN>
<OPTIONAL_USERTOKEN>TEST_TENANT_ID=001</OPTIONAL_USERTOKEN>

###
### HTTP operations for testing with the Visual Studio REST Client
###
### This code was generated by CodeGen, but will not be replaced
### when you regenerate code. If you wish to regenerate the Content
### of this file then delete the file before regenerating.
###

@protocol = <SERVER_PROTOCOL>
@hostname = <SERVER_NAME>
@port = <SERVER_HTTPS_PORT>
@bridgepath = <INTERFACE_NAME>
@tenantid = <TEST_TENANT_ID>
@baseuri = {{protocol}}://{{hostname}}:{{port}}/{{bridgepath}}

<METHOD_LOOP>
###
### <METHOD_NAME>
###

  <IF IN_OR_INOUT>
POST {{baseuri}}
Content-Type:application/json
Accept:application/json
  <IF DEFINED_ENABLE_MULTI_TENANCY>
x-tenant-id: "{{tenantid}}"
  </IF>

{ <PARAMETER_LOOP><IF IN_OR_INOUT>"<PARAMETER_NAME>": <PARAMETER_SAMPLE_DATA><IF MORE_IN_OR_INOUT>,</IF MORE_IN_OR_INOUT></IF IN_OR_INOUT></PARAMETER_LOOP> }

  <ELSE>
GET {{baseuri}}/<METHOD_NAME>
Accept:application/json

  </IF IN_OR_INOUT>
</METHOD_LOOP>
