<CODEGEN_FILENAME>MethodDispatcher.dbl</CODEGEN_FILENAME>
<REQUIRES_CODEGEN_VERSION>5.6.7</REQUIRES_CODEGEN_VERSION>
;//****************************************************************************
;//
;// Title:       InterfaceSuperDispatcher.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Creates a main dispatcher consolidates one or more interface
;//              specific dispacher classes.
;//
;// Copyright (c) 2021, Synergex International, Inc. All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;;*****************************************************************************
;;
;; Title:       MethodDispatcherDispatcher.dbl
;;
;; Description: Declares dispacher classes for exposed methods from one or more
;;              interfaces.
;;
;;*****************************************************************************
;; WARNING: GENERATED CODE!
;; This file was generated by CodeGen. Avoid editing the file if possible.
;; Any changes you make will be lost of the file is re-generated.
;;*****************************************************************************

import Harmony.TraditionalBridge
import <NAMESPACE>

namespace <NAMESPACE>

    public class MethodDispatcher

        public static method GetDispatchers, [#]@RoutineDispatcher
            record
                dispatchers, [#]@RoutineDispatcher
            endrecord
        proc
            dispatchers = new RoutineDispatcher[<COUNTER_1_RESET><INTERFACE_LOOP><COUNTER_1_INCREMENT></INTERFACE_LOOP><COUNTER_1_VALUE>]
<COUNTER_1_RESET>
<INTERFACE_LOOP>
<COUNTER_1_INCREMENT>
            dispatchers[<COUNTER_1_VALUE>] = new <INTERFACE_NAME>Dispatcher()
</INTERFACE_LOOP>
            mreturn dispatchers
        endmethod

    endclass

endnamespace