<CODEGEN_FILENAME><INTERFACE_NAME>TestRequests.dbl</CODEGEN_FILENAME>
<REQUIRES_CODEGEN_VERSION>5.4.6</REQUIRES_CODEGEN_VERSION>
<REQUIRES_USERTOKEN>MODELS_NAMESPACE</REQUIRES_USERTOKEN>
;//****************************************************************************
;//
;// Title:       InterfaceTestRequests.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: 
;//
;// Copyright (c) 2021, Synergex International, Inc. All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;;*****************************************************************************
;;
;; Title:       <INTERFACE_NAME>TestRequests.dbl
;;
;; Description: 
;;              
;;
;;*****************************************************************************
;; WARNING: GENERATED CODE!
;; This file was generated by CodeGen. Avoid editing the file if possible.
;; Any changes you make will be lost of the file is re-generated.
;;*****************************************************************************

import Newtonsoft.Json
import System
import System.IO

import <MODELS_NAMESPACE>

namespace <NAMESPACE>

    public static class <INTERFACE_NAME>TestRequests

        public static method MakeTestRequestFiles, void
        proc
            data testDataFolder = UnitTestEnvironment.FindRelativeFolderForAssembly("TestData")
            data fileSpec, string

<METHOD_LOOP>
  <IF IN_OR_INOUT>
            fileSpec = Path.Combine(testDataFolder,"<INTERFACE_NAME>.<METHOD_NAME>.request.json.template")
            data <METHOD_NAME>Request = new <INTERFACE_NAME>.<METHOD_NAME>_Request()
    <PARAMETER_LOOP>
      <IF IN_OR_INOUT AND REQUIRED>
            <METHOD_NAME>Request.<PARAMETER_NAME> = <HARMONYCORE_PARAMETER_SAMPLE_DATA>
      </IF>
    </PARAMETER_LOOP>
            File.WriteAllText(fileSpec, JsonConvert.SerializeObject(<METHOD_NAME>Request,Formatting.Indented))
            clear <METHOD_NAME>Request

  </IF>
</METHOD_LOOP>
        endmethod

    endclass

endnamespace
