<CODEGEN_FILENAME><INTERFACE_NAME>TestResponses.dbl</CODEGEN_FILENAME>
<REQUIRES_CODEGEN_VERSION>5.4.2</REQUIRES_CODEGEN_VERSION>
;//****************************************************************************
;//
;// Title:       InterfaceTestResponse.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Generates test responses for all OUT and INOUT parameters
;//
;// Copyright (c) 2019, Synergex International, Inc. All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;;*****************************************************************************
;;
;; Title:       <INTERFACE_NAME>TestResponses.dbl
;;
;; Description: Generates test responses for all OUT and INOUT parameters
;;
;;*****************************************************************************
;; WARNING: GENERATED CODE!
;; This file was generated by CodeGen. Avoid editing the file if possible.
;; Any changes you make will be lost of the file is re-generated.
;;*****************************************************************************

namespace <NAMESPACE>

    public class <INTERFACE_NAME>TestResponses

  <METHOD_LOOP>
    <IF RETURNS_DATA>
        public static method <METHOD_NAME>, <IF FUNCTION><IF HATVAL>i4<ELSE><method_return_type></IF HATVAL><ELSE>void</IF FUNCTION>
      <PARAMETER_LOOP>
        <IF OUT_OR_INOUT>
            <parameter_required> <parameter_direction> <PARAMETER_NAME>, <parameter_definition>
        </IF OUT_OR_INOUT>
      </PARAMETER_LOOP>
        proc
      <PARAMETER_LOOP>
        <IF OUT_OR_INOUT>
            <IF OPTIONAL>
            if (^passed(<PARAMETER_NAME>))
                <PARAMETER_NAME> = <PARAMETER_SAMPLE_DATA>
            <ELSE>
            <PARAMETER_NAME> = <PARAMETER_SAMPLE_DATA>
            </IF OPTIONAL>
        </IF OUT_OR_INOUT>
      </PARAMETER_LOOP>
      <IF FUNCTION>
            mreturn <IF ALPHA>"Z"</IF ALPHA><IF DECIMAL>9</IF DECIMAL><IF ENUM>8</IF ENUM><IF HATVAL>0</IF HATVAL><IF IMPLIED>6.6</IF IMPLIED><IF INTEGER>0</IF INTEGER>
      </IF FUNCTION>
        endmethod

    </IF RETURNS_DATA>
  </METHOD_LOOP>
    endclass

endnamespace

;
; Sample code to call these test methods
;
<METHOD_LOOP>
<IF RETURNS_DATA>
<IF FUNCTION>
;    freturn <INTERFACE_NAME>TestResponses.<METHOD_NAME>(<PARAMETER_LOOP><IF OUT_OR_INOUT><PARAMETER_NAME><IF MORE_OUT_OR_INOUT>,</IF MORE_OUT_OR_INOUT></IF OUT_OR_INOUT></PARAMETER_LOOP>)
<ELSE>
;    <INTERFACE_NAME>TestResponses.<METHOD_NAME>(<PARAMETER_LOOP><IF OUT_OR_INOUT><PARAMETER_NAME><IF MORE_OUT_OR_INOUT>,</IF MORE_OUT_OR_INOUT></IF OUT_OR_INOUT></PARAMETER_LOOP>)
;    xreturn
</IF FUNCTION>
</IF RETURNS_DATA>
</METHOD_LOOP>
