<CODEGEN_FILENAME><INTERFACE_NAME>MethodStubs.dbl</CODEGEN_FILENAME>
<REQUIRES_USERTOKEN>MODELS_NAMESPACE</REQUIRES_USERTOKEN>
<REQUIRES_CODEGEN_VERSION>5.7.8</REQUIRES_CODEGEN_VERSION>
;//****************************************************************************
;//
;// Title:       InterfaceMethodStubs.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Generates method stubs for methods defined in an InterfaceMethodStubs
;//              in a Synergy method catalog.
;//
;// Copyright (c) 2021, Synergex International, Inc. All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;;*****************************************************************************
;;
;; Title:       <INTERFACE_NAME>MethodStubs.dbl
;;
;; Description: Method stubs for interface <INTERFACE_NAME>
;;
;;*****************************************************************************
;; WARNING: GENERATED CODE!
;; This file was generated by CodeGen. Avoid editing the file if possible.
;; Any changes you make will be lost of the file is re-generated.
;;*****************************************************************************

import System.Collections
import <MODELS_NAMESPACE>

<METHOD_LOOP>
;;--------------------------------------------------------------------------------------------------
;; <METHOD_ROUTINE><IF COMMENT> (<METHOD_COMMENT>)</IF>
;;
<IF CUSTOM_METHOD_NO_STUB>
;; Stub generation has been disabled for this method.
;;

<ELSE>
<METHOD_ATTRIBUTE>
;;; <summary>
;;; <METHOD_COMMENT>
;;; </summary>
<PARAMETER_LOOP>
;;; <param name="<PARAMETER_NAME>"><PARAMETER_COMMENT></param>
</PARAMETER_LOOP>
<IF FUNCTION>
;;; <returns><METHOD_RETURN_COMMENT></returns>
</IF>
<method_type> <METHOD_ROUTINE><IF FUNCTION>, <METHOD_RETURN_TYPE></IF>
<PARAMETER_LOOP>
    <PARAMETER_ATTRIBUTE>
    <parameter_required> <parameter_direction_pad> <PARAMETER_NAME>, <PARAMETER_DEFINITION>
</PARAMETER_LOOP>
<IF FUNCTION>
    stack record
        retval, <IF HATVAL>i4<ELSE><method_return_type></IF>
    endrecord
</IF>
proc
<IF FUNCTION>
    init retval
    freturn retval
<ELSE>
    xreturn
</IF>
end<method_type>

</IF>
</METHOD_LOOP>
