<CODEGEN_FILENAME><StructureNoplural>Tests.dbl</CODEGEN_FILENAME>
<REQUIRES_CODEGEN_VERSION>5.4.6</REQUIRES_CODEGEN_VERSION>
<REQUIRES_OPTION>TF</REQUIRES_OPTION>
<CODEGEN_FOLDER>UnitTests</CODEGEN_FOLDER>
<REQUIRES_USERTOKEN>CLIENT_MODELS_NAMESPACE</REQUIRES_USERTOKEN>
<REQUIRES_USERTOKEN>SERVICES_NAMESPACE</REQUIRES_USERTOKEN>
;//****************************************************************************
;//
;// Title:       ODataUnitTests.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Generates unit tests for Web API / OData controllers in a
;//              Harmony Core environment.
;//
;// Copyright (c) 2018, Synergex International, Inc. All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;;*****************************************************************************
;;
;; Title:       <StructureNoplural>Tests.dbl
;;
;; Description: Unit tests for the operations defined in <StructurePlural>Controller.
;;
;;*****************************************************************************
;; WARNING: GENERATED CODE!
;; This file was generated by CodeGen. Avoid editing the file if possible.
;; Any changes you make will be lost of the file is re-generated.
;;*****************************************************************************

import Microsoft.AspNetCore.JsonPatch
import Microsoft.VisualStudio.TestTools.UnitTesting
import Newtonsoft.Json
import System.Collections.Generic
import System.Net.Http
import System.Net
import <SERVICES_NAMESPACE>
import <CLIENT_MODELS_NAMESPACE>

namespace <NAMESPACE>

    {TestClass}
    public partial class <StructureNoplural>Tests

        ;;------------------------------------------------------------
        ;;Get all <StructurePlural>

        {TestMethod}
        {TestCategory("<StructureNoplural> Tests - Read All")}
        public method Get<StructurePlural>, void
        proc
            disposable data client = UnitTestEnvironment.Server.CreateClient()
            <IF DEFINED_ENABLE_AUTHENTICATION>
            client.SetBearerToken(UnitTestEnvironment.AccessToken)
            </IF DEFINED_ENABLE_AUTHENTICATION>
            disposable data response = client.GetAsync("/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>").Result
            data result = response.Content.ReadAsStringAsync().Result
            response.EnsureSuccessStatusCode()
            data <structurePlural>, @OData<StructurePlural>, JsonConvert.DeserializeObject<OData<StructurePlural>>(result)
        endmethod

<IF DEFINED_ENABLE_RELATIONS>
  <IF STRUCTURE_RELATIONS>
    <RELATION_LOOP_RESTRICTED>
        ;;------------------------------------------------------------
        ;;Get all <StructurePlural> and expand relation <HARMONYCORE_RELATION_NAME>

        {TestMethod}
        {TestCategory("<StructureNoplural> Tests - Read All")}
        <IF MANY_TO_ONE_TO_MANY>
        public method Get<StructurePlural>_Expand_<HARMONYCORE_RELATION_NAME>, void
        proc
            data uri = "/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>?$expand=<HARMONYCORE_RELATION_NAME>"
        </IF MANY_TO_ONE_TO_MANY>
        <IF ONE_TO_ONE>
        public method Get<StructurePlural>_Expand_<HARMONYCORE_RELATION_NAME>, void
        proc
            data uri = "/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>?$expand=<HARMONYCORE_RELATION_NAME>"
        </IF ONE_TO_ONE>
        <IF ONE_TO_MANY_TO_ONE>
        public method Get<StructurePlural>_Expand_<HARMONYCORE_RELATION_NAME>, void
        proc
            data uri = "/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>?$expand=<HARMONYCORE_RELATION_NAME>"
        </IF ONE_TO_MANY_TO_ONE>
        <IF ONE_TO_MANY>
        public method Get<StructurePlural>_Expand_<HARMONYCORE_RELATION_NAME>, void
        proc
            data uri = "/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>?$expand=<HARMONYCORE_RELATION_NAME>"
        </IF ONE_TO_MANY>
            disposable data client = UnitTestEnvironment.Server.CreateClient()
            <IF DEFINED_ENABLE_AUTHENTICATION>
            client.SetBearerToken(UnitTestEnvironment.AccessToken)
            </IF DEFINED_ENABLE_AUTHENTICATION>
            disposable data response = client.GetAsync(uri).Result
            data result = response.Content.ReadAsStringAsync().Result
            response.EnsureSuccessStatusCode()
        endmethod

    </RELATION_LOOP_RESTRICTED>
        ;;------------------------------------------------------------
        ;;Get all <StructurePlural> and expand all relations

        {TestMethod}
        {TestCategory("<StructureNoplural> Tests - Read All")}
        public method Get<StructurePlural>_Expand_All, void
        proc
            data uri = "/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>?$expand=<RELATION_LOOP_RESTRICTED><IF MANY_TO_ONE_TO_MANY><HARMONYCORE_RELATION_NAME></IF MANY_TO_ONE_TO_MANY><IF ONE_TO_ONE><HARMONYCORE_RELATION_NAME></IF ONE_TO_ONE><IF ONE_TO_MANY_TO_ONE><HARMONYCORE_RELATION_NAME></IF ONE_TO_MANY_TO_ONE><IF ONE_TO_MANY><HARMONYCORE_RELATION_NAME></IF ONE_TO_MANY><,></RELATION_LOOP_RESTRICTED>"
            disposable data client = UnitTestEnvironment.Server.CreateClient()
            <IF DEFINED_ENABLE_AUTHENTICATION>
            client.SetBearerToken(UnitTestEnvironment.AccessToken)
            </IF DEFINED_ENABLE_AUTHENTICATION>
            disposable data response = client.GetAsync(uri).Result
            data result = response.Content.ReadAsStringAsync().Result
            response.EnsureSuccessStatusCode()
        endmethod
        
  </IF STRUCTURE_RELATIONS>
</IF DEFINED_ENABLE_RELATIONS>
        ;;------------------------------------------------------------
        ;;Get a single <StructureNoplural> by primary key

        {TestMethod}
        {TestCategory("<StructureNoplural> Tests - Read by Primary Key")}
        public method Get<StructureNoplural>, void
        proc
            data client = UnitTestEnvironment.Server.CreateClient()
            <IF DEFINED_ENABLE_AUTHENTICATION>
            client.SetBearerToken(UnitTestEnvironment.AccessToken)
            </IF DEFINED_ENABLE_AUTHENTICATION>
            data request = String.Format("/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>(<PRIMARY_KEY><SEGMENT_LOOP><SegmentName>=<IF ALPHA>'</IF ALPHA>{<SEGMENT_NUMBER>}<IF ALPHA>'</IF ALPHA><,></SEGMENT_LOOP>)","",<SEGMENT_LOOP>TestConstants.Get<StructureNoplural>_<SegmentName><,></SEGMENT_LOOP></PRIMARY_KEY>)
            data response = client.GetAsync(request).Result
            data result = response.Content.ReadAsStringAsync().Result
            response.EnsureSuccessStatusCode()
            data <structureNoplural>, @OData<StructureNoplural>, JsonConvert.DeserializeObject<OData<StructureNoplural>>(result)
        endmethod

<IF DEFINED_ENABLE_RELATIONS>
  <IF STRUCTURE_RELATIONS>
    <RELATION_LOOP_RESTRICTED>
        ;;------------------------------------------------------------
        ;;Get a single <StructureNoplural> by primary key and expand relation <IF MANY_TO_ONE_TO_MANY><HARMONYCORE_RELATION_NAME></IF MANY_TO_ONE_TO_MANY><IF ONE_TO_ONE><HARMONYCORE_RELATION_NAME></IF ONE_TO_ONE><IF ONE_TO_MANY_TO_ONE><HARMONYCORE_RELATION_NAME></IF ONE_TO_MANY_TO_ONE><IF ONE_TO_MANY><HARMONYCORE_RELATION_NAME></IF ONE_TO_MANY>

        {TestMethod}
        {TestCategory("<StructureNoplural> Tests - Read by Primary Key")}
        public method Get<StructureNoplural>_Expand_<IF MANY_TO_ONE_TO_MANY><HARMONYCORE_RELATION_NAME></IF MANY_TO_ONE_TO_MANY><IF ONE_TO_ONE><HARMONYCORE_RELATION_NAME></IF ONE_TO_ONE><IF ONE_TO_MANY_TO_ONE><HARMONYCORE_RELATION_NAME></IF ONE_TO_MANY_TO_ONE><IF ONE_TO_MANY><HARMONYCORE_RELATION_NAME></IF ONE_TO_MANY>, void
        proc
            data client = UnitTestEnvironment.Server.CreateClient()
            <IF DEFINED_ENABLE_AUTHENTICATION>
            client.SetBearerToken(UnitTestEnvironment.AccessToken)
            </IF DEFINED_ENABLE_AUTHENTICATION>
            data request = String.Format("/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>(<PRIMARY_KEY><SEGMENT_LOOP><SegmentName>=<IF ALPHA>'</IF ALPHA>{<SEGMENT_NUMBER>}<IF ALPHA>'</IF ALPHA><,></SEGMENT_LOOP></PRIMARY_KEY>)?$expand=<IF MANY_TO_ONE_TO_MANY><HARMONYCORE_RELATION_NAME></IF MANY_TO_ONE_TO_MANY><IF ONE_TO_ONE><HARMONYCORE_RELATION_NAME></IF ONE_TO_ONE><IF ONE_TO_MANY_TO_ONE><HARMONYCORE_RELATION_NAME></IF ONE_TO_MANY_TO_ONE><IF ONE_TO_MANY><HARMONYCORE_RELATION_NAME></IF ONE_TO_MANY>","",<PRIMARY_KEY><SEGMENT_LOOP>TestConstants.Get<StructureNoplural>_Expand_<IF MANY_TO_ONE_TO_MANY><HARMONYCORE_RELATION_NAME></IF MANY_TO_ONE_TO_MANY><IF ONE_TO_ONE><HARMONYCORE_RELATION_NAME></IF ONE_TO_ONE><IF ONE_TO_MANY_TO_ONE><HARMONYCORE_RELATION_NAME></IF ONE_TO_MANY_TO_ONE><IF ONE_TO_MANY><HARMONYCORE_RELATION_NAME></IF ONE_TO_MANY>_<SegmentName><,></SEGMENT_LOOP></PRIMARY_KEY>)
            data response = client.GetAsync(request).Result
            data result = response.Content.ReadAsStringAsync().Result
            response.EnsureSuccessStatusCode()
            data <structureNoplural>, @OData<StructureNoplural>, JsonConvert.DeserializeObject<OData<StructureNoplural>>(result)
        endmethod

    </RELATION_LOOP_RESTRICTED>
        ;;------------------------------------------------------------
        ;;Get a single <StructureNoplural> by primary key and expand all relations

        {TestMethod}
        {TestCategory("<StructureNoplural> Tests - Read by Primary Key")}
        public method Get<StructureNoplural>_Expand_All, void
        proc
            data client = UnitTestEnvironment.Server.CreateClient()
            <IF DEFINED_ENABLE_AUTHENTICATION>
            client.SetBearerToken(UnitTestEnvironment.AccessToken)
            </IF DEFINED_ENABLE_AUTHENTICATION>
            data request = String.Format("/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>(<PRIMARY_KEY><SEGMENT_LOOP><SegmentName>=<IF ALPHA>'</IF ALPHA>{<SEGMENT_NUMBER>}<IF ALPHA>'</IF ALPHA><,></SEGMENT_LOOP></PRIMARY_KEY>)?$expand=<RELATION_LOOP_RESTRICTED><IF MANY_TO_ONE_TO_MANY><HARMONYCORE_RELATION_NAME></IF MANY_TO_ONE_TO_MANY><IF ONE_TO_ONE><HARMONYCORE_RELATION_NAME></IF ONE_TO_ONE><IF ONE_TO_MANY_TO_ONE><HARMONYCORE_RELATION_NAME></IF ONE_TO_MANY_TO_ONE><IF ONE_TO_MANY><HARMONYCORE_RELATION_NAME></IF ONE_TO_MANY><,></RELATION_LOOP_RESTRICTED>","",<PRIMARY_KEY><SEGMENT_LOOP>TestConstants.Get<StructureNoplural>_Expand_All_<SegmentName><,></SEGMENT_LOOP></PRIMARY_KEY>)
            data response = client.GetAsync(request).Result
            data result = response.Content.ReadAsStringAsync().Result
            response.EnsureSuccessStatusCode()
            data <structureNoplural>, @OData<StructureNoplural>, JsonConvert.DeserializeObject<OData<StructureNoplural>>(result)
        endmethod

  </IF STRUCTURE_RELATIONS>
</IF DEFINED_ENABLE_RELATIONS>
<IF DEFINED_ENABLE_ALTERNATE_KEYS>
<ALTERNATE_KEY_LOOP>
        ;;------------------------------------------------------------
        ;;Get a single <StructureNoplural> by alternate key <KEY_NUMBER> (<KeyName>)

        {TestMethod}
        {TestCategory("<StructureNoplural> Tests - Read by Alternate Key")}
        public method Get<StructureNoplural>_ByAltKey_<KeyName>, void
        proc
            data client = UnitTestEnvironment.Server.CreateClient()
            <IF DEFINED_ENABLE_AUTHENTICATION>
            client.SetBearerToken(UnitTestEnvironment.AccessToken)
            </IF DEFINED_ENABLE_AUTHENTICATION>
            data request = String.Format("/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>(<SEGMENT_LOOP><SegmentName>=<IF ALPHA>'</IF ALPHA>{<SEGMENT_NUMBER>}<IF ALPHA>'</IF ALPHA><,></SEGMENT_LOOP>)", "", <SEGMENT_LOOP>TestConstants.Get<StructureNoplural>_ByAltKey_<KeyName>_<SegmentName><IF DATE>.ToString("yyyy-MM-dd")</IF DATE><,></SEGMENT_LOOP>)
            data response = client.GetAsync(request).Result
            data result = response.Content.ReadAsStringAsync().Result
            response.EnsureSuccessStatusCode()
<IF DUPLICATES>
            data <structurePlural>, @OData<StructurePlural>,JsonConvert.DeserializeObject<OData<StructurePlural>>(result)
<ELSE>
            data <structureNoplural>, @OData<StructureNoplural>,JsonConvert.DeserializeObject<OData<StructureNoplural>>(result)
</IF DUPLICATES>
        endmethod

</ALTERNATE_KEY_LOOP>
</IF DEFINED_ENABLE_ALTERNATE_KEYS>
;//        ;;------------------------------------------------------------
;//        ;;Create a new <StructureNoplural> (auto assign key)
;//
;//        {TestMethod}
;//        {TestCategory("<StructureNoplural> Tests - Create, Update & Delete")}
;//        public method Create<StructureNoplural>, void
;//        proc
;//            disposable data client = UnitTestEnvironment.Server.CreateClient()
;//            <IF DEFINED_ENABLE_AUTHENTICATION>
;//            client.SetBearerToken(UnitTestEnvironment.AccessToken)
;//            </IF DEFINED_ENABLE_AUTHENTICATION>
;//            disposable data requestBody = new StringContent("")
;//            disposable data response = client.PostAsync("/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>", requestBody).Result
;//            data result = response.Content.ReadAsStringAsync().Result
;//            response.EnsureSuccessStatusCode()
;//        endmethod
;//
<IF DEFINED_ENABLE_PUT>
<IF DEFINED_ENABLE_PATCH>
<IF DEFINED_ENABLE_DELETE>
        ;;------------------------------------------------------------
        ;;Create new <StructureNoplural> (client specified key)

        {TestMethod}
        {TestCategory("<StructureNoplural> Tests - Create, Update & Delete")}
        public method Update<StructureNoplural>, void
        proc
            disposable data client = UnitTestEnvironment.Server.CreateClient()
            <IF DEFINED_ENABLE_AUTHENTICATION>
            client.SetBearerToken(UnitTestEnvironment.AccessToken)
            </IF DEFINED_ENABLE_AUTHENTICATION>

            ;;Get one <structureNoplural> from the file
            data getRequest = String.Format("/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>(<PRIMARY_KEY><SEGMENT_LOOP><IF ALPHA>'</IF ALPHA>{<SEGMENT_NUMBER>}<IF ALPHA>'</IF ALPHA><,></SEGMENT_LOOP>)","",<SEGMENT_LOOP>TestConstants.Get<StructureNoplural>_<SegmentName><,></SEGMENT_LOOP></PRIMARY_KEY>)
            data getResponse = client.GetAsync(getRequest).Result
            data getResult = getResponse.Content.ReadAsStringAsync().Result

            ;;Check that we got a successful response from the web service
            getResponse.EnsureSuccessStatusCode()

            ;;Deserialize the JSON into a <StructureNoplural> object
            data do<StructureNoplural>, @<StructureNoplural>, JsonConvert.DeserializeObject<<StructureNoplural>>(getResult)

            <PRIMARY_KEY>
            <SEGMENT_LOOP>
            do<StructureNoplural>.<FieldSqlName> = TestConstants.Update<StructureNoplural>_<SegmentName>
            </SEGMENT_LOOP>
            </PRIMARY_KEY>

            ;TODO: Also need to ensure any nodups alternate keys get unique values

            ;;Create new item
            disposable data requestBody = new StringContent(JsonConvert.SerializeObject(do<StructureNoplural>),System.Text.Encoding.UTF8, "application/json")
            data request = String.Format("/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>(<PRIMARY_KEY><SEGMENT_LOOP><IF ALPHA>'</IF ALPHA>{<SEGMENT_NUMBER>}<IF ALPHA>'</IF ALPHA><,></SEGMENT_LOOP>)","",<SEGMENT_LOOP>TestConstants.Update<StructureNoplural>_<SegmentName><,></SEGMENT_LOOP></PRIMARY_KEY>)
            disposable data response = client.PutAsync(request, requestBody).Result

            ;;Check that we got a successful response from the web service
            response.EnsureSuccessStatusCode()

            ;;Get the inserted record
            getResponse = client.GetAsync(request).Result
            getResult = getResponse.Content.ReadAsStringAsync().Result

            ;;Check that we got a successful response from the web service
            getResponse.EnsureSuccessStatusCode()

            ;;Deserialize the JSON into a <StructureNoplural> object
            do<StructureNoplural> = JsonConvert.DeserializeObject<<StructureNoplural>>(getResult)

            ;;Change the first non key field to test full update
            <COUNTER_1_RESET>
            <FIELD_LOOP>
            <IF NOTKEYSEGMENT>
            <IF USED_IN_RELATION>
            <ELSE>
            <COUNTER_1_INCREMENT>
            <IF COUNTER_1_EQ_1>
            <IF ALPHA>
            do<StructureNoplural>.<FieldSqlName> = "Y"
            <ELSE>
            do<StructureNoplural>.<FieldSqlName> = 8
            </IF ALPHA>
            </IF COUNTER_1_EQ_1>
            </IF USED_IN_RELATION>
            </IF NOTKEYSEGMENT>
            </FIELD_LOOP>

            ;;Update full item
            requestBody = new StringContent(JsonConvert.SerializeObject(do<StructureNoplural>),System.Text.Encoding.UTF8, "application/json")
            request = String.Format("/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>(<PRIMARY_KEY><SEGMENT_LOOP><IF ALPHA>'</IF ALPHA>{<SEGMENT_NUMBER>}<IF ALPHA>'</IF ALPHA><,></SEGMENT_LOOP>)","",<SEGMENT_LOOP>TestConstants.Update<StructureNoplural>_<SegmentName><,></SEGMENT_LOOP></PRIMARY_KEY>)
            response = client.PutAsync(request, requestBody).Result

            ;;Check that we got a successful response from the web service
            response.EnsureSuccessStatusCode()

            ;;Get the inserted record
            getResponse = client.GetAsync(request).Result
            getResult = getResponse.Content.ReadAsStringAsync().Result

            ;;Check that we got a successful response from the web service
            getResponse.EnsureSuccessStatusCode()

            ;;Deserialize the JSON into a <StructureNoplural> object
            do<StructureNoplural> = JsonConvert.DeserializeObject<<StructureNoplural>>(getResult)

            <COUNTER_1_RESET>
            <FIELD_LOOP>
            <IF NOTKEYSEGMENT>
            <IF USED_IN_RELATION>
            <ELSE>
            <COUNTER_1_INCREMENT>
            <IF COUNTER_1_EQ_1>
            <IF ALPHA>
            Assert.AreEqual(do<StructureNoplural>.<FieldSqlName>, "Y")
            <ELSE>
            Assert.AreEqual(do<StructureNoplural>.<FieldSqlName>, 8)
            </IF ALPHA>
            </IF COUNTER_1_EQ_1>
            </IF USED_IN_RELATION>
            </IF NOTKEYSEGMENT>
            </FIELD_LOOP>


            ;;Update one non-existant property in the customer
            data badPatchDoc = new JsonPatchDocument()
            badPatchDoc.Replace("xyzzy", "Z")

            ;;Serialize the bad patch to JSON
            data badSerializedPatch = JsonConvert.SerializeObject(badPatchDoc)

            ;;Apply the bad patch
            disposable data badPatchRequestBody = new StringContent(badSerializedPatch,System.Text.Encoding.UTF8, "application/json-patch+json")
            disposable data badPatchResponse = client.PatchAsync(request, badPatchRequestBody).Result
            ;;Check that we got a failure response from the web service
            Assert.AreEqual(badPatchResponse.StatusCode, HttpStatusCode.BadRequest)

            ;;Update one property in the <structureNoplural>
            data patchDoc = new JsonPatchDocument()
            <COUNTER_1_RESET>
            <FIELD_LOOP>
            <IF NOTKEYSEGMENT>
            <IF USED_IN_RELATION>
            <ELSE>
            <COUNTER_1_INCREMENT>
            <IF COUNTER_1_EQ_1>
            <IF ALPHA>
            patchDoc.Replace("<FieldSqlName>", "Z")
            <ELSE>
            patchDoc.Replace("<FieldSqlName>", "9")
            </IF ALPHA>
            </IF COUNTER_1_EQ_1>
            </IF USED_IN_RELATION>
            </IF NOTKEYSEGMENT>
            </FIELD_LOOP>

            ;;Serialize the patch to JSON
            data serializedPatch = JsonConvert.SerializeObject(patchDoc)

            ;;Apply the patch
            disposable data patchRequestBody = new StringContent(serializedPatch,System.Text.Encoding.UTF8, "application/json-patch+json")
            disposable data patchResponse = client.PatchAsync(request, patchRequestBody).Result

            ;;Check that we got a successful response from the web service
            patchResponse.EnsureSuccessStatusCode()

            ;;Get the updated <structureNoplural> record
            getResponse = client.GetAsync(request).Result
            getResult = getResponse.Content.ReadAsStringAsync().Result

            ;;Check that we got a successful response from the web service
            getResponse.EnsureSuccessStatusCode()

            ;;Deserialize the JSON into a <StructureNoplural> object
            do<StructureNoplural> = JsonConvert.DeserializeObject<<StructureNoplural>>(getResult)

            ;;Verify that the property was changed
            <COUNTER_1_RESET>
            <FIELD_LOOP>
            <IF NOTKEYSEGMENT>
            <IF USED_IN_RELATION>
            <ELSE>
            <COUNTER_1_INCREMENT>
            <IF COUNTER_1_EQ_1>
            <IF ALPHA>
            Assert.AreEqual(do<StructureNoplural>.<FieldSqlName>, "Z")
            <ELSE>
            Assert.AreEqual(do<StructureNoplural>.<FieldSqlName>, 9)
            </IF ALPHA>
            </IF COUNTER_1_EQ_1>
            </IF USED_IN_RELATION>
            </IF NOTKEYSEGMENT>
            </FIELD_LOOP>

            ;;Delete It
            disposable data deleteResponse = client.DeleteAsync(request).Result

            ;;Check that we got a successful response from the web service
            getResponse.EnsureSuccessStatusCode()

            ;;Attempt to get the deleted record
            getResponse = client.GetAsync(request).Result

            ;;Check we got a fail state from the web service
            Assert.AreEqual(getResponse.IsSuccessStatusCode, false)

        endmethod

</IF DEFINED_ENABLE_DELETE>
</IF DEFINED_ENABLE_PATCH>
</IF DEFINED_ENABLE_PUT>
;//<PRIMARY_KEY>
;//<IF MULTIPLE_SEGMENTS>
;//        ;;------------------------------------------------------------
;//        ;;Get multiple <StructureNoplural> by partial primary key
;//
;//        {TestMethod}
;//        {TestCategory("<StructureNoplural> Tests - Read by Primary Key")}
;//        public method Get<StructureNoplural>_ByPartialPrimaryKey, void
;//        proc
;//            data client = UnitTestEnvironment.Server.CreateClient()
;//            <IF DEFINED_ENABLE_AUTHENTICATION>
;//            client.SetBearerToken(UnitTestEnvironment.AccessToken)
;//            </IF DEFINED_ENABLE_AUTHENTICATION>
;//            data request = String.Format("/odata<IF DEFINED_ENABLE_API_VERSIONING>/v<API_VERSION></IF DEFINED_ENABLE_API_VERSIONING>/<StructurePlural>(<SEGMENT_LOOP_FILTER><SegmentName>=<IF ALPHA>'</IF ALPHA>{<SEGMENT_NUMBER>}<IF ALPHA>'</IF ALPHA><,></SEGMENT_LOOP_FILTER>)","",<SEGMENT_LOOP_FILTER>TestConstants.Get<StructureNoplural>_ByPartialPrimaryKey_<SegmentName><,></SEGMENT_LOOPFILTER>)
;//            data response = client.GetAsync(request).Result
;//            data result = response.Content.ReadAsStringAsync().Result
;//            response.EnsureSuccessStatusCode()
;//            data <structureNoplural>, @OData<StructureNoplural>, JsonConvert.DeserializeObject<OData<StructureNoplural>>(result)
;//        endmethod
;//
;//</IF MULTIPLE_SEGMENTS>
;//</PRIMARY_KEY>
    endclass

endnamespace
