<CODEGEN_FILENAME><StructureNoplural>.dbl</CODEGEN_FILENAME>
<REQUIRES_CODEGEN_VERSION>5.3.6</REQUIRES_CODEGEN_VERSION>
<REQUIRES_OPTION>TF</REQUIRES_OPTION>
<CODEGEN_FOLDER>Models</CODEGEN_FOLDER>
;//****************************************************************************
;//
;// Title:       ODataClientModel.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Creates model classes suitable for use in OData clients.
;//
;// Copyright (c) 2018, Synergex International, Inc. All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;;*****************************************************************************
;;
;; Title:       <StructureNoplural>.dbl
;;
;; Description: OData model class representing data defined by the repository
;;              structure <STRUCTURE_NOALIAS> and from the data file <FILE_NAME>.
;;
;;*****************************************************************************
;; WARNING: GENERATED CODE!
;; This file was generated by CodeGen. Avoid editing the file if possible.
;; Any changes you make will be lost of the file is re-generated.
;;*****************************************************************************

import Newtonsoft.Json
import System.Collections.Generic

namespace <NAMESPACE>

    public partial class <StructureNoplural>

<FIELD_LOOP>
    <IF CUSTOM_NOT_HARMONY_EXCLUDE>
        ;;; <summary>
        ;;; <FIELD_DESC>
        ;;; </summary>
        <IF CUSTOM_HARMONY_AS_STRING>
        public readwrite property <FieldSqlname>, String
        <ELSE>
        public readwrite property <FieldSqlname>, <FIELD_CSTYPE>
        </IF CUSTOM_HARMONY_AS_STRING>

    </IF CUSTOM_NOT_HARMONY_EXCLUDE>
</FIELD_LOOP>
    endclass

    public class OData<StructureNoplural>
        
        {JsonProperty("odata.metadata")}
        public readwrite property Metadata, string
        {JsonProperty("value")}
        public readwrite property Value, @<StructureNoplural>

    endclass

    public class OData<StructurePlural>
        
        {JsonProperty("odata.metadata")}
        public readwrite property Metadata, string
        {JsonProperty("value")}
        public readwrite property Value, @List<<StructureNoplural>>

    endclass

endnamespace
